#:schema https://github.com/YunoHost/apps/blob/main/schemas/antifeatures.toml.schema.json

[tracking]
description.en = "Tracks you and/or reports your activity to upstream maintainer or third parties, either without your permission or by default."
description.eu = "Zure jardueraren jarraipena egiten du eta/edo jardueraren berri ematen die aplikazioaren arduradunari edo hirugarrenei, baimenik gabe edo defektuz."
description.fr = "Vous piste et/ou rapporte vos activités au mainteneur source ou à des tiers, sans votre permission ou par défaut."
description.it = "Ti traccia e/o riporta la tua attività a chi mantiene il codice sorgente o a terze parti, facendolo senza il tuo permesso o di default."
icon = "user-secret"
title.en = "Tracking"
title.eu = "Jarraipena"
title.fr = "Pistage "
title.it = "Tracciamento"

[non-free-network]
description.en = "Promotes or depends entirely on a non-free network service."
description.eu = "Librea ez den sare-zerbitzu bat sustatzen du edo horren mende dago erabat."
description.fr = "Promeut ou utilise des services réseau non libres."
description.it = "Promuove o dipende interamente da servizi di rete non liberi."
icon = "sitemap"
title.en = "Non-free Network Services"
title.eu = "Libreak ez diren sareko zerbitzuak"
title.fr = "Services réseau non libres "
title.it = "Servizi di rete non liberi"

[non-free-addons]
description.en = "Promotes other non-free applications or plugins."
description.eu = "Libreak ez diren beste aplikazio edo gehigarri batzuk sustatzen ditu."
description.fr = "Promeut d'autres applications ou plugins non libres."
description.it = "Promoove altre applicazioni o plugin non liberi"
icon = "puzzle-piece"
title.en = "Non-free Addons"
title.eu = "Libreak ez diren gehigarriak"
title.fr = "Extensions non libres "
title.it = "Estensioni non libere"

[non-free-dependencies]
description.en = "Relies on software dependencies that are not free in order to run."
description.eu = "Libreak ez diren dependentzien mende dago exekutatu ahal izateko."
description.fr = "Dépend pour fonctionner de dépendances logicielles non libres."
description.it = "Per funzionare, si basa su dipendenze software non libere."
icon = "book"
title.en = "Non-free dependencies"
title.eu = "Libreak ez diren dependentziak"
title.fr = "Dépendances non libres "
title.it = "Dipendenze non libere"

[non-free-assets]
description.en = "Contains and makes use of non-free assets. The most common case is apps using artwork - images, sounds, music, etc. - under a commercial license."
description.eu = "Libreak ez diren baliabideak ditu eta erabiltzen ditu. Kasurik ohikoena artelanak (irudiak, soinuak, musika, etab.) erabiltzen dituzten aplikazioak dira. - jabedun-lizentziapean."
description.fr = "Contient ou utilise des médias non libres. Le cas le plus fréquent concerne des applications utilisant des œuvres (images, sons, musiques, etc.) sous une licence commerciale."
description.it = "Contiene ed utilizza risorse mediatiche non libere. Il caso più comune è l’utilizzo da parte dell’app di contenuti artistici (immagini, suoni, musica, ecc.) coperti da licenza commerciale."
icon = "file-image-o"
title.en = "Non-free assets"
title.eu = "Libreak ez diren baliabideak"
title.fr = "Ressources non libres "
title.it = "Risorse non libere"

[bad-security-reputation]
description.en = "Has a bad security reputation, such as deprecated addons."
description.eu = "Segurtasun ospe txarra du, utzitako gehigarriak esaterako."
description.fr = "A une mauvaise réputation en matière de sécurité, en utilisant des plugins dépréciés par exemple."
description.it = "Ha una cattiva reputazione in termini di sicurezza (per esempio, potrebbe utilizzare addon obsoleti)."
icon = "bug"
title.en = "Bad security reputation"
title.eu = "Segurtasun txarreko ospea"
title.fr = "Mauvaise réputation en matière de sécurité "
title.it = "Cattiva reputazione di sicurezza"

[deprecated-software]
description.en = "This software is not maintained anymore. Expect it to break down over time, be exposed to unfixed security breaches, etc."
description.eu = "Software honek ez du arduradunik. Denborak aurrera egin ahala funtzionatzeari utziko dio, konpondu gabeko segurtasun arazoak izango ditu, etab."
description.fr = "Ce logiciel n'est plus maintenu. Attendez-vous à ce qu'il ne fonctionne plus avec le temps, et que l'on découvre des failles de sécurité qui ne seront pas corrigées, etc."
description.it = "Questo software non è più mantenuto. Ci si può aspettare che con il passare del tempo smetta di funzionare, sia esposto a falle di sicurezza, ecc."
icon = "trash-o"
title.en = "Upstream not maintained"
title.eu = "Jatorrizko garapena utzita"
title.fr = "Application non maintenue "
title.it = "Applicazione non mantenuta"

[package-not-maintained]
description.en = "This YunoHost package is not actively maintained and needs adoption. This means that minimal maintenance is made by volunteers who don't use the app, so you should expect the app to lose reliability over time. You can [learn how to package](https://yunohost.org/packaging_apps_intro) if you'd like to adopt it."
description.eu = "YunoHost pakete honek ez du mantenduko duenik, bere gain hartuko duen norbaiten beharra dauka. Honek esan nahi duena da mantentze-lanak minimoak izango direla eta aplikazioa erabiltzen ez duten boluntarioek egingo dituztela lanok; denborak aurrera egin ahala fidagarri izateari utziko dio. [Aplikazioak nola paketatu](https://yunohost.org/packaging_apps_intro) ikas dezakezu, zure gain hartu nahi baduzu."
description.fr = "Ce package YunoHost n'est pas activement maintenu et a besoin d'être adopté. Cela veut dire que la maintenance minimale est réalisée par des bénévoles qui n'utilisent pas l'application, il faut donc s'attendre à ce que l'app perde en fiabilité avec le temps. Vous pouvez [apprendre comment packager](https://yunohost.org/packaging_apps_intro) si vous voulez l'adopter."
description.it = "Questo pacchetto YunoHost non viene mantenuto attivamente e deve essere adottato. Ciò significa che la manutenzione minima è effettuata da volontari che non usano l'applicazione, quindi ci si deve aspettare che l'applicazione perda affidabilità nel tempo. È possibile [imparare a pacchettizzare](https://yunohost.org/packaging_apps_intro) se si desidera adottarla."
icon = "user-times"
title.en = "Package not maintained"
title.eu = "Mantendu gabeko paketea"
title.fr = "Package non maintenu "
title.it = "Pacchetto non mantenuto"

[paid-content]
description.en = "Promotes or depends, entirely or partially, on a paid service."
description.eu = "Ordainpeko zerbitzu bat sustatzen du edo bere mende dago, osorik edo neurri batean."
description.fr = "Promeut ou dépend, entièrement ou partiellement, d'un service payant."
description.it = "Promuove o dipende, interamente o parzialmente, da un servizio a pagamento."
icon = "money"
title.en = "Paid content"
title.eu = "Ordainpeko edukia"
title.fr = "Contenu payant "
title.it = "Contenuti a pagamento"

[arbitrary-limitations]
description.en = "Features arbitrary limitations. Please refer to the README."
description.eu = "Muga arbitrarioak ditu. Irakurri README fitxategia."
description.fr = "Contient des limitations arbitraires. Se référer au fichier README."
description.it = "Contiene limitazioni arbitrarie. Fare riferimento al file “README”."
icon = "star-half-empty"
title.en = "Arbitrary limitations"
title.eu = "Muga arbitrarioak"
title.fr = "Limitations arbitraires "
title.it = "Limitazioni arbitrarie"

[replaced-by-another-app]
description.en = "Was replaced by another app. Please refer to the README."
description.eu = "Beste aplikazio batek ordeztu du. Irakurri README fitxategia."
description.fr = "A été remplacé par une autre application. Se référer au fichier README."
description.it = "Quest’app è stata sostituita da un’altra app. Fare riferimento al file “README”."
icon = "repeat"
title.en = "Replaced by another app"
title.eu = "Beste aplikazio batek ordeztu du"
title.fr = "Remplacé par une autre application "
title.it = "Sostituita da un’altra app"

[alpha-software]
description.en = "Early development stage. May contain changing or unstable features, bugs, and security vulnerability."
description.eu = "Garapenaren hasierako fasean dago. Ezaugarri aldakor edo ezegonkorrak, erroreak eta segurtasun-arazoak izan ditzazke."
description.fr = "Le logiciel est au tout début de son développement. Il pourrait contenir des fonctionnalités changeantes ou instables, des bugs, et des failles de sécurité."
description.it = "Questo software è all’inizio della sua fase di sviluppo. Potrebbe dunque essere instabile, contenere bug e vulnerabilità di sicurezza."
icon = "flask"
title.en = "Alpha software"
title.eu = "Alfa softwarea"
title.fr = "Logiciel en version alpha "
title.it = "Software in versione alpha"

[not-totally-free-upstream]
description.en = "The packaged app is under an overall free license, but with clauses that may restrict its use."
description.eu = "Aplikazioak lizentzia librea du orokorrean, baina bere erabilera mugatzen duten klausulekin."
description.fr = "L'application packagée est sous une licence globalement libre, mais avec des clauses qui pourraient restreindre son utilisation."
description.it = "Quest’applicazione è protetta da licenza generalmente libera, ma con delle clausole che potrebbero limitare il suo utilizzo."
icon = "lock"
title.en = "Not totally free upstream"
title.eu = "Jatorrizkoa ez da erabat librea"
title.fr = "Application sous licence libre restreinte "
title.it = "Applicazione con licenza parzialmente libera"

[not-totally-free-package]
description.en = "The YunoHost package of this app is under an overall free license, but with clauses that may restrict its use."
description.eu = "Aplikazio honen YunoHost paketeak lizentzia librea du orokorrean, baina bere erabilera mugatzen duten klausulekin."
description.fr = "Le package YunoHost de cette application est sous une licence globalement libre, mais avec des clauses qui pourraient restreindre son utilisation."
icon = "archive"
title.en = "Not totally free package"
title.eu = "Paketea ez da erabat librea"
title.fr = "Package sous licence libre restreinte "
